name: rFSM
run-name: ${{ github.actor }} has invoked github action ðŸš€
on: [push, workflow_dispatch]
jobs:
  total:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies. lua, luarocks, luacov
        run: .github/workflows/dependencies.sh

      - name : unit tests lua 5.1
        run: |
          tests/run_tests.sh -i lua5.1 --clean --coverage

      - name : unit tests lua 5.2
        run: |
          tests/run_tests.sh -i lua5.2 --clean= --coverage

      - name : unit tests lua 5.3
        run: |
          tests/run_tests.sh -i lua5.3 --clean= --coverage

      - name : unit tests lua 5.4
        run: |
          tests/run_tests.sh -i lua5.4 --clean= --coverage

      - name: ðŸš€ Archive coverage reports
        uses: actions/upload-artifact@v4
        with:
          path: tests/luacov.report.out.*

      - run: echo "This job's status is ${{ job.status }}."
